/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.AgendaController;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author darkm
 */



public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;
    
    /**
     * Creates new form Agenda
     */
    
    
    
    public Agenda() {
        initComponents();
        controller = new AgendaController(this);
        jTextData = new JFormattedTextField(new SimpleDateFormat("dd/MM/yyyy"));
        jTextHora = new JFormattedTextField(new SimpleDateFormat("HH:mm"));
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAgendar = new javax.swing.JButton();
        jScrollPanetabela = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jScrollPaneObservacao = new javax.swing.JScrollPane();
        jTextObservacao = new javax.swing.JTextArea();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jComboBoxServico = new javax.swing.JComboBox<>();
        jTextValor = new javax.swing.JTextField();
        jTextId = new javax.swing.JTextField();
        jTextHora = new javax.swing.JTextField();
        jTextData = new javax.swing.JTextField();
        agendaServico = new javax.swing.JLabel();
        agendaObservacao = new javax.swing.JLabel();
        agendaData = new javax.swing.JLabel();
        agendaId = new javax.swing.JLabel();
        agendaCliente = new javax.swing.JLabel();
        agendaValor = new javax.swing.JLabel();
        agendaHora = new javax.swing.JLabel();
        jLabelSombra = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1926, 1080));
        setSize(new java.awt.Dimension(1926, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAgendar.setBackground(new java.awt.Color(0, 255, 51));
        jButtonAgendar.setText("Agendar");
        jButtonAgendar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 255, 153), new java.awt.Color(102, 255, 102)));
        jButtonAgendar.setOpaque(true);
        jButtonAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 390, 30));

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, "15/07/2024", "09:30", null},
                {null, null, null, null, "15/07/2024", "10:00", null},
                {null, null, null, null, "15/07/2024", "10:30", null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cliente", "Serviço", "Valor R$", "Data", "Hora", "Observação"
            }
        ));
        jScrollPanetabela.setViewportView(jTabela);

        getContentPane().add(jScrollPanetabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 920, 180));

        jTextObservacao.setColumns(20);
        jTextObservacao.setRows(5);
        jScrollPaneObservacao.setViewportView(jTextObservacao);

        getContentPane().add(jScrollPaneObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 390, 210));

        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 200, -1));

        jComboBoxServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxServicoItemStateChanged(evt);
            }
        });
        jComboBoxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 200, -1));

        jTextValor.setText("0.0");
        jTextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 200, -1));

        jTextId.setText("1");
        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });
        getContentPane().add(jTextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 200, -1));

        jTextHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHoraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 200, -1));

        jTextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDataActionPerformed(evt);
            }
        });
        getContentPane().add(jTextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 200, -1));

        agendaServico.setForeground(new java.awt.Color(255, 255, 255));
        agendaServico.setText("Serviço");
        getContentPane().add(agendaServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        agendaObservacao.setForeground(new java.awt.Color(255, 255, 255));
        agendaObservacao.setText("Observação");
        getContentPane().add(agendaObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 80, -1));

        agendaData.setForeground(new java.awt.Color(255, 255, 255));
        agendaData.setText("Data");
        getContentPane().add(agendaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        agendaId.setForeground(new java.awt.Color(255, 255, 255));
        agendaId.setText("Id");
        getContentPane().add(agendaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 10, -1));

        agendaCliente.setForeground(new java.awt.Color(255, 255, 255));
        agendaCliente.setText("Cliente");
        getContentPane().add(agendaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        agendaValor.setForeground(new java.awt.Color(255, 255, 255));
        agendaValor.setText("Valor R$");
        getContentPane().add(agendaValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        agendaHora.setForeground(new java.awt.Color(255, 255, 255));
        agendaHora.setText("Hora");
        getContentPane().add(agendaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        jLabelSombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/teste (1).png"))); // NOI18N
        getContentPane().add(jLabelSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 1070, 520));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/tela de agenda.png"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDataActionPerformed

    private void jComboBoxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServicoActionPerformed

    private void jTextHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHoraActionPerformed

    private void jTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdActionPerformed

    private void jButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarActionPerformed
        this.controller.agendar();
    }//GEN-LAST:event_jButtonAgendarActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jTextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValorActionPerformed

    private void jComboBoxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxServicoItemStateChanged
        this.controller.atualizaValor();
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServicoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agendaCliente;
    private javax.swing.JLabel agendaData;
    private javax.swing.JLabel agendaHora;
    private javax.swing.JLabel agendaId;
    private javax.swing.JLabel agendaObservacao;
    private javax.swing.JLabel agendaServico;
    private javax.swing.JLabel agendaValor;
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxServico;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelSombra;
    private javax.swing.JScrollPane jScrollPaneObservacao;
    private javax.swing.JScrollPane jScrollPanetabela;
    private javax.swing.JTable jTabela;
    private javax.swing.JTextField jTextData;
    private javax.swing.JTextField jTextHora;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextArea jTextObservacao;
    private javax.swing.JTextField jTextValor;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaServico();
        this.controller.atualizaValor();
    }

    public JTable getjTabela() {
        return jTabela;
    }

    public void setjTabela(JTable jTabela) {
        this.jTabela = jTabela;
    }

    public JComboBox<String> getjComboBoxCliente() {
        return jComboBoxCliente;
    }

    public void setjComboBoxCliente(JComboBox<String> jComboBoxCliente) {
        this.jComboBoxCliente = jComboBoxCliente;
    }

    public JComboBox<String> getjComboBoxServico() {
        return jComboBoxServico;
    }

    public void setjComboBoxServico(JComboBox<String> jComboBoxServico) {
        this.jComboBoxServico = jComboBoxServico;
    }

    public JTextField getjTextValor() {
        return jTextValor;
    }

    public void setjTextValor(JTextField jTextValor) {
        this.jTextValor = jTextValor;
    }

    public JTextField getjTextData() {
        return jTextData;
    }

    public void setjTextData(JTextField jTextData) {
        this.jTextData = jTextData;
    }

    public JTextField getjTextHora() {
        return jTextHora;
    }

    public void setjTextHora(JTextField jTextHora) {
        this.jTextHora = jTextHora;
    }

    public JTextField getjTextId() {
        return jTextId;
    }

    public void setjTextId(JTextField jTextId) {
        this.jTextId = jTextId;
    }

    public JTextArea getjTextObservacao() {
        return jTextObservacao;
    }

    public void setjTextObservacao(JTextArea jTextObservacao) {
        this.jTextObservacao = jTextObservacao;
    }

    public JTextField getDataFormatada() {
        return jTextData; // Certifique-se de que jTextData é um JTextField ou JFormattedTextField
    }

    public JTextField getHoraFormatada() {
        return jTextHora; // Certifique-se de que jTextHora é um JTextField ou JFormattedTextField
    }


}